kind: pipeline
name: caiso-iso

workspace:
 base: /code

steps:
- name: git-tag-hash
  image: alpine/git
  commands:
  - echo -n "$(git log --pretty=format:'%h' -n 1)" >> .tags
  when:
    event:
    - push
    - tag

- name: git-tag-latest
  image: alpine/git
  commands:
  - echo -n ",latest" >> .tags
  when:
    branch:
      include:
      - master

