kind: pipeline
name: caiso-iso

workspace:
 base: /code

steps:
- name: git-tag-hash
  image: alpine/git
  commands:
  - echo -n "$(git log --pretty=format:'%h' -n 1)" >> .tags
  - cat .tags

- name: git-tag-latest
  image: alpine/git
  commands:
  - echo -n ",latest" >> .tags
  - cat .tags
  - echo ${DRONE_TAG}

